### ISSUE TITLE
Оптимизация вычислений

### ISSUE THREAD

**Issue by spogozhev** [asavershin/PM-PU#1]
https://github.com/asavershin/PM-PU/blob/bc3453d4b4345dde8b1b7c7890e9f5dc654a04ed/homeworks/04.10.2021/rhombus/main.cpp#L13

Для того, чтобы на каждом шаге цикла не вычислять при проверке условий abs ((n - k) % n), следует вычислить значение этого выражения один раз перед циклом и сохранить значение в какой-нибудь переменной. К тому же, данная величина используется и в других циклах. 
Второй вариант - цикл сделать в обратном порядке, чтобы выражение вычислялось в момент инициализации, а проверка условия была бы простой (типа i>=0).

**Comment by asavershin** [comment]
Сделаю вычисление этого выражения в отдельную переменную в главном цикле, потому что k идет как счетчик.
